[package]
name = "iron-demo"
version = "0.1.0"
authors = ["Felipe@MBP2 <auditor400@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iron="0.6.1"
params="0.8.0"
reqwest="0.9"

